### PR TITLE
Add docs badge to README

### PR DESCRIPTION
**Pull request by rrrene**
Hi there,

didn't we talk a week ago via Twitter? Sorry if I did not get back to you ...

This PR fixes Travis and adds the Inch CI badge: [Inline docs](http://inch-ci.org/github/Kosmas/pleaguer)

Hope you like Elixir so far. Welcome to the community!

### CODE REVIEW

**Comment by Kosmas** [comment]
@rrrene hi,

Yes we did talk :-) and you did get back to me!!

Thanks for this too!

And nice to find you in the Elixir world too :-)

**Comment by rrrene** [comment]
@Kosmas Hi, I will reply here instead of Twitter to have more than 140 chars :wink: 

I changed the `:only` setting of the `inch_ex` dependency from `docs` to `test` because - in a Phoenix app - we load `config/#{Mix.env}.exs`. This tried to load `config/docs.exs` which failed because the file does not exist. 

So we could have either changed the `:only` setting for the dep or created an empty `config/docs.exs`, both would have worked.

**Comment by Kosmas** [comment]
@rrrene  I understand now.
Is there anything I could help you with?
If you need any help use the email in my profile here :-)

**Comment by rrrene** [comment]
I might take you up on that as soon as I have published a new version :wink:

**Comment by Kosmas** [comment]
:+1:

**Pull request merged**
